### ISSUE TITLE
Unable to use Docker image - "new tesla service: new oauth2 client: open: open oauth2_config.json: no such file or directory"

### ISSUE THREAD

**Issue by wywywywy** [uhthomas/tesla_exporter#49]
I'm getting the following error when I try to run the Docker image with this - `docker run -e TOKEN=qts-xxx ghcr.io/uhthomas/tesla_exporter`

```
new tesla service: new oauth2 client: open: open oauth2_config.json: no such file or directory
```

Does it even use the `TOKEN` environment variable? I can't find any reference of it in the repo.

**Comment by uhthomas** [comment]
Good morning 😄 

Apologies for the inconvenience, you're correct. The documentation needs to be updated to reflect the changes as part of https://github.com/uhthomas/tesla_exporter/commit/33e5c166b98da8f5ec3a30f14a6c9dfbe70befd9.

Please refer to this [Kubernetes deployment](https://github.com/uhthomas/automata/blob/a90d7055495108c5b5bff9a3d2909f2f97aafab2/k8s/mahalo/tesla_exporter/deployment_list.cue#L46-L47) for an end-to-end example in the meantime.

**Comment by wywywywy** [comment]
That's cool. Thank you.

What format are `oauth2_config.json` & `oauth2_token.json` in please?

**Comment by uhthomas** [comment]
Hey, I've [updated the README](https://github.com/uhthomas/tesla_exporter/commit/67f52a06cd15681598c267e7d8cdf4d3d51c8f51). Hopefully this clears things up.

It's documented this in the README, but for brevity `oauth2_config.json` and `oauth2_token.json` are then JSON encoding of [oauth2.Config](https://pkg.go.dev/golang.org/x/oauth2#Config) and [oauth2.Token](https://pkg.go.dev/golang.org/x/oauth2#Token).
