### ISSUE TITLE
oauth state value should not be static

### ISSUE THREAD

**Issue by borgstrom** [uhthomas/tesla_exporter#5]
Hi @uhthomas, 👋 

I ended up here from https://github.com/timdorr/tesla-api/issues/215 as my code broke today like many others.

While reviewing your implementation I noticed that you set a static state value:

https://github.com/uhthomas/tesla_exporter/blob/65c70ce0ede7c90cfd4fe234a523db41801ea9e7/cmd/login/client.go#L111

The state should be "a unique and non-guessable value"; https://auth0.com/docs/protocols/state-parameters

Thanks again for participating in the @timdorr issue. My code is also in Go, so using your code as reference is great for me :)

**Comment by uhthomas** [comment]
Good spot! Thank you. Will push a fix in a sec.
